### ISSUE TITLE
font-awesome_5

### ISSUE THREAD

**Issue by Lahim26** [marska/MMM-Looko2-aq#1]
I was not able to use font-awesome_5 icons in other modules (squares in spite of icons).
I had to comment out / cancel line in MagicMirror/modules/MMM-Looko2-aq/MMM-Looko2-aq.js
` getStyles: function() {
                return ["MMM-Looko2-aq.css", /* "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" */];
        },

` 
And after that, new icons were visible. So, since the new relases of MagicMirror already contain font-awesome (see this post https://github.com/MichMich/MagicMirror/pull/1345) I suggest to include only MMM-Looko2-aq.css

**Comment by marska** [comment]
@Lahim26 Yes, you're right. I fixed it. Thanks.

Better late than never. :)
